feat(@formatjs/cli): allow custom Formatter with Node API
formatjs/formatjs pull request #2143
Opened 2020-09-24 16:49 UTC by bertho-zero

2020-09-24 17:48 UTC, bertho-zero commented
CI fails with

```
Running //packages/cli:prettier
[error] No parser could be inferred for file: packages/cli/lib/cli.d.ts.map
[error] No parser could be inferred for file: packages/cli/lib/cli.js.map
[error] No parser could be inferred for file: packages/cli/lib/console_utils.d.ts.map
[error] No parser could be inferred for file: packages/cli/lib/console_utils.js.map
[error] No parser could be inferred for file: packages/cli/lib/extract.d.ts.map
[error] No parser could be inferred for file: packages/cli/lib/extract.js.map
[error] No parser could be inferred for file: packages/cli/lib/index.d.ts.map
[error] No parser could be inferred for file: packages/cli/lib/index.js.map
```

2020-09-25 01:48 UTC, longlho requested changes

2020-09-25 01:48 UTC, longlho commented on packages/cli/src/formatters/index.ts
> +    return Promise.resolve().then(() => format);
you can just `return format` here right?

2020-09-25 21:33 UTC, longlho approved these changes

2020-09-25 21:33 UTC, merged

2020-09-25 21:33 UTC, longlho commented
Thanks a lot for your contributions!