feat(@formatjs/intl,react-intl): move IntlFormatter type parameters to methods
formatjs/formatjs pull request #3858
Opened 2022-10-01 01:35 UTC by pyrocat101

Fixes https://github.com/formatjs/formatjs/issues/3856

This PR moves the type parameter of `IntlFormatters<T = any, R = T>` to each individual methods. Now methods such as `formatMessage` will have two type parameters. This change should type check the callsites more accurately, as the return type should really be determined by the type you interpolate into the message.

2022-10-01 03:48 UTC, longlho requested changes

2022-10-01 03:48 UTC, longlho commented on packages/intl/src/types.ts
> +  formatMessage<T = any, R = T>(
ideally react-intl should be able to set `T` to `ReactNode` while things like `vue-intl` or `ember-intl` can set this to something else. I don't see how we can achieve that w/ this?

2022-10-08 23:05 UTC, pyrocat101 commented
I probably butchered the typing of `vue-intl`. Anyone who knows Vue should probably review my change there.

2022-10-09 01:34 UTC, longlho commented on packages/intl/src/list.ts
> +  values: ReadonlyArray<string>,
it can take rich text values right?

2022-10-11 02:46 UTC, merged